# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1e28b15d89ecfa2063ed835cf8173c9d7829ef0c9adb8eeddc3247b801e5d6f6559256b6eb1cff8acccd8ece654094eb9487cdca1849979090ad4d0903faa7

test:
  secret_key_base: 52984686759d23194fcda351f46a6f0aeee5c45456b0fd4cc281614655bad60a5fa6f9fa589073d5e3490864e487ca9245012227a6678345b0f8ccedd395131f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
